/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    public void testCityAggregation() {
        // Sample CSV lines
        java.util.List<String> lines = java.util.Arrays.asList(
            "id,name,age,city",
            "1,John Doe,30,New York",
            "2,Jane Smith,25,Los Angeles",
            "3,Bob Johnson,40,New York",
            "4,Alice Williams,35,Chicago"
        );

        java.util.concurrent.ConcurrentHashMap<String, Integer> cityCounts = App.aggregateCities(lines);
        assertEquals(2, cityCounts.get("New York"));
        assertEquals(1, cityCounts.get("Los Angeles"));
        assertEquals(1, cityCounts.get("Chicago"));
    }
}
